# Generated by Django 5.2.17 on 2026-09-29 05:17

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='resumes/'),
        ),
    ]
